WITH MastersDemographics AS (
SELECT ED.EmployeeID, ED.FirstName, ED.Age
FROM [SQLTUTORIAL].DBO.EMPLOYEEDEMOGRAPHICS AS ED
UNION ALL
SELECT WD.EmployeeID, WD.FirstName, WD.Age
FROM [SQLTUTORIAL].DBO.WarehouseEmployeeDemographics AS WD) , 
AGEGROUPSTABLE AS(
SELECT EmployeeID, Age, 
CASE
WHEN AGE > 40 THEN '40 AND OVER'
ELSE 'UNDER 40'
END AS AGEGROUPS
FROM MastersDemographics), 
AVERAGESALARY AS (
SELECT DISTINCT agegroupstable.AGEGROUPS, avg(es.Salary) over (partition by agegroupstable.agegroups) AS AVERAGESALARYFOREACHAGEGROUP
FROM AGEGROUPSTABLE
LEFT JOIN [SQLTUTORIAL].DBO.EmployeeSalary as es
ON AGEGROUPSTABLE.EMPLOYEEID = ES.EmployeeID)

select *
from AVERAGESALARY
